// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package gocmd

import (
	"context"
	"sync"
)

var (
	lockCommandMockBuild sync.RWMutex
	lockCommandMockGet   sync.RWMutex
)

// CommandMock is a mock implementation of Command.
//
//     func TestSomethingThatUsesCommand(t *testing.T) {
//
//         // make and configure a mocked Command
//         mockedCommand := &CommandMock{
//             BuildFunc: func(ctx context.Context, pkgs ...string) error {
// 	               panic("TODO: mock out the Build method")
//             },
//             GetFunc: func(ctx context.Context, pkgs ...string) error {
// 	               panic("TODO: mock out the Get method")
//             },
//         }
//
//         // TODO: use mockedCommand in code that requires Command
//         //       and then make assertions.
//
//     }
type CommandMock struct {
	// BuildFunc mocks the Build method.
	BuildFunc func(ctx context.Context, pkgs ...string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, pkgs ...string) error

	// calls tracks calls to the methods.
	calls struct {
		// Build holds details about calls to the Build method.
		Build []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pkgs is the pkgs argument value.
			Pkgs []string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pkgs is the pkgs argument value.
			Pkgs []string
		}
	}
}

// Build calls BuildFunc.
func (mock *CommandMock) Build(ctx context.Context, pkgs ...string) error {
	if mock.BuildFunc == nil {
		panic("CommandMock.BuildFunc: method is nil but Command.Build was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Pkgs []string
	}{
		Ctx:  ctx,
		Pkgs: pkgs,
	}
	lockCommandMockBuild.Lock()
	mock.calls.Build = append(mock.calls.Build, callInfo)
	lockCommandMockBuild.Unlock()
	return mock.BuildFunc(ctx, pkgs...)
}

// BuildCalls gets all the calls that were made to Build.
// Check the length with:
//     len(mockedCommand.BuildCalls())
func (mock *CommandMock) BuildCalls() []struct {
	Ctx  context.Context
	Pkgs []string
} {
	var calls []struct {
		Ctx  context.Context
		Pkgs []string
	}
	lockCommandMockBuild.RLock()
	calls = mock.calls.Build
	lockCommandMockBuild.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *CommandMock) Get(ctx context.Context, pkgs ...string) error {
	if mock.GetFunc == nil {
		panic("CommandMock.GetFunc: method is nil but Command.Get was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Pkgs []string
	}{
		Ctx:  ctx,
		Pkgs: pkgs,
	}
	lockCommandMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockCommandMockGet.Unlock()
	return mock.GetFunc(ctx, pkgs...)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedCommand.GetCalls())
func (mock *CommandMock) GetCalls() []struct {
	Ctx  context.Context
	Pkgs []string
} {
	var calls []struct {
		Ctx  context.Context
		Pkgs []string
	}
	lockCommandMockGet.RLock()
	calls = mock.calls.Get
	lockCommandMockGet.RUnlock()
	return calls
}
